# development.yml
# Copyright (C) 2023  Squidpie

---
name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:
    name: Squidtest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "â˜ï¸ checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "ğŸ”§ build squidbot"
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -S. -B./targets/debug
          cmake --build ./targets/debug -j32 --target all squidtest

      - name: "ğŸ”§ build docker"
        run: docker build -t squidbot --build-arg build_dir=./targets/debug/ .

      - name: "ğŸ” run squidtest"
        run: ./targets/debug/test/bin/squidtest

      - name: "ğŸ” run docker test"
        run: docker run squidbot:latest /squidbot/bin/squidbot --test
