# development.yml
# Copyright (C) 2023  Squidpie

name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:
    name: Squidtest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "â˜ï¸ checkout"
        uses: actions/checkout@v3

      - name:  "ğŸ”§ build"
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -S. -B./targets/debug
          cmake --build ./targets/debug -j32 --target squidtest

      - name: "ğŸ”§ clang install"
        run: sudo apt-get install clang
      
      - name: "ğŸ”§ linter"
        uses: cpp-linter/cpp-linter-action@v2.4.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          database: ${GITHUB_WORKSPACE}/targets/debug/compile_commands.json

      - name: "ğŸ” linter fail check"
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1

      - name: "ğŸ” test"
        run: ./targets/debug/bin/squidtest
