# development.yml
# Copyright (C) 2023  Squidpie

name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:
    name: Squidtest
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: "â˜ï¸ checkout"
        uses: actions/checkout@v3

      - name:  "ğŸ”§ build"
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -S. -B./targets/
          cmake --build ./targets -j16
        
      - name: "ğŸ” linting"
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: "linting fail check"
        if: steps.linter.outputs.checks-failed > 0
        run: echo "DEBUG OUTPUT LINTING FAILED"

      - name: "ğŸ” test"
        run: ./targets/bin/test/squidtest
